# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0002_auto_20160224_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredient')),
            ],
        ),
    ]
