# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0003_ingredientinstance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='type',
            field=models.CharField(blank=True, choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], max_length=2),
        ),
    ]
