# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 00:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0004_auto_20160225_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasedIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('product', models.CharField(default='', max_length=100)),
                ('brand', models.CharField(blank=True, default='', max_length=100)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredient')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredientinstance',
            name='ingredient',
        ),
        migrations.DeleteModel(
            name='IngredientInstance',
        ),
    ]
