# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:33
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0007_auto_20160225_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedingredient',
            name='volume',
            field=django_measurement.models.MeasurementField(default=0.0, measurement_class='Volume'),
        ),
    ]
