# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0009_auto_20160225_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
