# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_purchasedingredient_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomemadeIngredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('defaultrecipe', models.IntegerField(null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredient')),
                ('recipes', models.ManyToManyField(to='cocktails.Recipe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
