# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 03:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_homemadeingredient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CocktailRecipe',
            fields=[
                ('recipe_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cocktails.Recipe')),
                ('ingredients', models.ManyToManyField(to='cocktails.Ingredient')),
            ],
            bases=('cocktails.recipe',),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='name',
        ),
        migrations.AddField(
            model_name='recipe',
            name='descriptor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
