# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0012_auto_20160225_0353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailrecipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='cocktailrecipe',
            name='recipe_ptr',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='cocktails.Ingredient'),
        ),
        migrations.DeleteModel(
            name='CocktailRecipe',
        ),
    ]
