# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0013_auto_20160225_0359'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cocktail',
        ),
        migrations.RemoveField(
            model_name='homemadeingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='homemadeingredient',
            name='recipes',
        ),
        migrations.RemoveField(
            model_name='purchasedingredient',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='HomemadeIngredient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='PurchasedIngredient',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
