# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0017_recipeentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeentry',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='recipeentry',
            name='ingredient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredient'),
        ),
    ]
