# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0021_auto_20160302_2032'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
