# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0022_cocktail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cocktail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.Cocktail'),
        ),
    ]
