# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0023_recipe_cocktail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeentry',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
