# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0024_recipeentry_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
