# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0026_auto_20160303_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipegroup',
            name='type',
            field=models.TextField(default='cocktail'),
        ),
    ]
