# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0027_recipegroup_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipegroup',
            name='type',
            field=models.CharField(default='cocktail', max_length=30),
        ),
    ]
