# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0028_auto_20160304_0134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=150)),
                ('slug', models.SlugField(blank=True, default='')),
                ('type', models.CharField(default='cocktail', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='group',
        ),
        migrations.DeleteModel(
            name='RecipeGroup',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cocktail',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.Cocktail'),
        ),
    ]
