# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0029_auto_20160304_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='description',
            field=models.TextField(blank=True, max_length=140),
        ),
    ]
