# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0030_cocktail_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
