# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0031_cocktail_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='index',
            new_name='rank',
        ),
    ]
