# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0032_auto_20160304_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='rank',
            field=models.IntegerField(default=1),
        ),
    ]
