# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 22:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0033_auto_20160304_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeentry',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cocktails.Ingredient'),
        ),
    ]
