# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0036_auto_20160310_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
