# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0038_auto_20160310_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(default='', error_messages={'unique': 'This name is already in use! Choose another?'}, max_length=150, unique=True),
        ),
    ]
