# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0039_auto_20160310_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeEntry',
            new_name='Entry',
        ),
        migrations.RemoveField(
            model_name='cocktail',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='type',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(default='', max_length=150, unique=True),
        ),
    ]
