# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0040_auto_20160310_2140'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set([('cocktail', 'rank')]),
        ),
    ]
