# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0041_auto_20160313_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='recipes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
