# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cocktails', '0044_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterUniqueTogether(
            name='cocktail',
            unique_together=set([('user', 'name'), ('user', 'slug')]),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('user', 'name'), ('user', 'slug')]),
        ),
    ]
