# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-23 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0045_auto_20160323_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
