# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-24 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0048_cocktail_recipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cocktails',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
